### ISSUE TITLE
Link soil profile data with core coordinate data

### ISSUE THREAD

**Issue by dklinges9** [whrc/Mangrove-Soil-Carbon#2]
@jsanderman @thengl @kysolvik 

Hello all,
In an effort to broadcast this synthesis and provide resources for the community, my team here at Smithsonian Enviro Research Center is hoping to incorporate the disaggregated data from this study into our [coastal carbon atlas](https://ccrcn.shinyapps.io/CoastalCarbonAtlas/). This map will inform current modeling and mapping work by a team that Jon is part of, and is also currently of interest to land managers and practitioners.

**My question:**
I'm hoping to link the [soil profile](https://github.com/whrc/Mangrove-Soil-Carbon/blob/master/depth_model_comparison/soil_profiles.csv) data with [the core-level data](https://github.com/whrc/Mangrove-Soil-Carbon/blob/master/R_code/41558_2018_162_MOESM2_ESM.csv), which includes the core coordinates. However, there's no linking keys between these two datasets (as in, none of the columns found in either of these files are found in the other file) even though it appears they represent the same cores, Is there any way to match the observations from one of the files to those of the other?

Thanks,
Dave Klinges
[Coastal Carbon Research Coordination Network](https://serc.si.edu/coastalcarbon)

**Comment by jsanderman** [comment]
Hi Dave, I'm not sure about the file with the core-level data -- that is something Tom added when he updated the model for TNC recently. 

I'll send you an excel file via email that has all the public horizon and site data with a clear site ID linking the two together (this is just an updated version of the file that is available on [Harvard Dataverse](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/OCYUIT) that I haven't gotten around to updating yet).

**Comment by thengl** [comment]
Hi Dave, I recommend using the `mangroves_SOC_points.gpkg` file for any further modeling / analysis, which you can download also from https://doi.org/10.5281/zenodo.1469347. Generation of this data is explained from https://github.com/whrc/Mangrove-Soil-Carbon/blob/master/R_code/GMW_mangroves_SOC_30m.R#L217 (note I actually use here a location ID, to avoid any duplicates even if they come with different ID).

**Comment by jsanderman** [comment]
Hi Tom, it looks like you have both the public and private data available in that file. You have to take it down and only include the data intended for public release. There were several datasets that we are not at liberty to share (the USFS data, most of the point data from the Sundarbans and a few other collections). The database up at Harvard Dataverse only contains the public data. 

Am I correct that the only addition to our data were the sites from Andre Rovai's paper? If so, Dave already has these data anyway.

**Comment by thengl** [comment]
Hi Jon. Did not know about the private data. Can you please send me a separate email with instructions on which points need to be masked out (best highlight in the Google spreadsheet). The R code shows which data is used and how. 

Yes in the update we only use additional points from Roval's paper.
